1. Write a function so that the columns of the output matrix are powers of the input
   vector.The order of the powers is determined by the increasing boolean argument. Specifically, when
   increasing is False, the i-th output column is the input vector raised element-wise to the power
   of N - i - 1.

In [16]:
import numpy as np

def vander_matrix(ipvector,n,increasing=False):
    
    if not increasing:
        out_matrix=np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        out_matrix=np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
        
    return out_matrix

ipvector=np.array([1,2,3,5,6])
no_columns=3
out_matrix_dec_order=vander_matrix(ipvector,no_columns,False)
out_matrix_inc_order=vander_matrix(ipvector,no_columns,True)

print('The Input Array is:',ipvector,'\n')
print('Vander Matrix of the input array in decreasing order of powers:\n',out_matrix_dec_order,'\n')
print('Vander Matrix of the input array in increasing order of powers:\n',out_matrix_inc_order,'\n')



The Input Array is: [1 2 3 5 6] 

Vander Matrix of the input array in decreasing order of powers:
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]
 [36  6  1]] 

Vander Matrix of the input array in increasing order of powers:
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]
 [ 1  6 36]] 



2.Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [18]:
import numpy as np

def movingavg(values,window):
    weights=np.repeat(1.0,window)/window
    seq=np.convolve(values,weights,'valid')
    return seq

dataset=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
movingavg(dataset,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])